# Generated by Django 3.0.6 on 2020-06-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediscape', '0003_auto_20200616_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.AddField(
            model_name='medicine',
            name='tags',
            field=models.ManyToManyField(to='mediscape.Tag'),
        ),
    ]
