# Generated by Django 3.0.6 on 2020-06-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediscape', '0004_auto_20200616_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
